[FIX] #71 - Add controller "pagenotfound" in nobots for Prestashop 1.6.1
ZiZuu-store/zzSEOtk pull request #72
Opened 2017-04-05 10:41 UTC by GuillaumeG22

2017-04-05 22:29 UTC, drAlberT requested changes
Hi @GuillaumeG22 ,
thanks for your contribution.

Can you plz amend your PR after having replaced tabs with spaces?

Thank you

2017-04-06 08:14 UTC, GuillaumeG22 commented
Hi @drAlberT,

It's ok for the tabs.

Guillaume

2017-04-06 16:04 UTC, drAlberT approved these changes

2017-04-06 16:05 UTC, drAlberT commented
closes #71

2017-04-06 16:05 UTC, merged